# Generated by Django 4.0.1 on 2022-01-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boro', models.CharField(choices=[('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('Manhattan', 'Manhattan'), ('Bronx', 'Bronx'), ('SI', 'Staten Island'), ('Nassau', 'Nassau')], max_length=10)),
                ('Date', models.DateField()),
                ('Flyer_image', models.ImageField(max_length=1, upload_to=None)),
                ('Event_type', models.CharField(choices=[('Comedy', 'Comedy'), ('Food/Drink', 'Food/Drink'), ('Athletic', 'Athletic'), ('Sports', 'Sports'), ('Seasonal', 'Seasonal'), ('Rock', 'Live Music: Rock'), ('HipHop', 'Live Music: HipHop'), ('Dance', 'Live Music: Dance'), ('Other', 'Live Music: Other')], max_length=10)),
                ('Contact_information', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
