# Generated by Django 4.0.1 on 2022-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Flyer_image',
            field=models.ImageField(max_length=200, upload_to=None),
        ),
    ]
