# Generated by Django 4.0.1 on 2022-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_flyer_flyer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Flyer_image',
            field=models.ImageField(max_length=200, upload_to='flyer_imgs/'),
        ),
    ]
