# Generated by Django 4.0.1 on 2022-01-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_date_flyer_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Boro',
            field=models.CharField(choices=[('brooklyn', 'Brooklyn'), ('queens', 'Queens'), ('manhattan', 'Manhattan'), ('bronx', 'Bronx'), ('staten', 'Staten Island'), ('nassau', 'Nassau')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='Event_type',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('food/drink', 'Food/Drink'), ('athletic', 'Athletic'), ('sports', 'Sports'), ('seasonal', 'Seasonal'), ('rock', 'Live Music: Rock'), ('hipHop', 'Live Music: HipHop'), ('dance', 'Live Music: Dance'), ('other', 'Live Music: Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_email', models.CharField(max_length=200)),
                ('Flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.flyer')),
            ],
        ),
    ]
