# Generated by Django 4.0.1 on 2022-01-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_flyer_boro_alter_flyer_event_type_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='Watched_Flyer',
        ),
    ]
