# Generated by Django 4.0.1 on 2022-01-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_watchlist_watched_flyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watched_Flyer',
            new_name='Reminder',
        ),
    ]
