# Generated by Django 4.0.1 on 2022-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_rename_watched_flyer_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Event_type',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('food', 'Food/Drink'), ('athletic', 'Athletic'), ('sports', 'Sports'), ('seasonal', 'Seasonal'), ('rock', 'Live Music: Rock'), ('hipHop', 'Live Music: HipHop'), ('dance', 'Live Music: Dance'), ('other', 'Live Music: Other')], max_length=10),
        ),
    ]
