# Generated by Django 3.2.4 on 2022-01-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20220128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
