# Generated by Django 3.2.4 on 2022-03-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_flyer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='Posistion',
            field=models.SmallIntegerField(null=True),
        ),
    ]
