# Generated by Django 3.2.4 on 2022-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_flyer_posted_by_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Posistion',
            field=models.SmallIntegerField(default=0),
        ),
    ]
