# Generated by Django 3.2.4 on 2022-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_flyer_posistion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Posted_by_me',
            field=models.BooleanField(default=False),
        ),
    ]
