# Generated by Django 3.2.4 on 2022-05-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_flyer_posted_by_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Flyer_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.flyer_image'),
        ),
    ]
