# Generated by Django 3.2.4 on 2022-05-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_flyer_flyer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer_image',
            name='Flyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.flyer'),
        ),
    ]
