# Generated by Django 3.2.4 on 2022-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_flyer_image_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer_image',
            name='Hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flyer_image',
            name='Url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flyer_image',
            name='Flyer_image',
            field=models.ImageField(null=True, upload_to='flyer_imgs/'),
        ),
    ]
