# Generated by Django 3.2.4 on 2022-05-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20220520_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer_image',
            name='Flyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.flyer'),
        ),
        migrations.AlterField(
            model_name='flyer_image',
            name='Flyer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flyer_imgs/'),
        ),
        migrations.AlterField(
            model_name='flyer_image',
            name='Hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flyer_image',
            name='Url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
