# Generated by Django 3.2.4 on 2022-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20220520_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='Description',
            field=models.CharField(default='desrpt', max_length=500),
            preserve_default=False,
        ),
    ]
