# Generated by Django 3.2.4 on 2022-06-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_flyer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Date', models.DateField()),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.flyer')),
            ],
        ),
    ]
