# Generated by Django 3.2.4 on 2022-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Event_date',
            field=models.DateField(null=True),
        ),
    ]
