# Generated by Django 3.2.4 on 2022-06-22 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_flyer_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Day_of_week',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
