# Generated by Django 3.2.4 on 2022-06-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_auto_20220621_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='Event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
