# Generated by Django 3.2.4 on 2022-06-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_auto_20220621_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.flyer'),
        ),
    ]
