# Generated by Django 3.2.4 on 2022-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20220706_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Contact_information',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
