# Generated by Django 3.2.4 on 2022-07-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_alter_flyer_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Description',
            field=models.CharField(default='Come by !', max_length=500),
        ),
    ]
