# Generated by Django 3.2.4 on 2022-08-01 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_alter_flyer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer_image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flyer',
            name='Description',
            field=models.CharField(blank=True, default='Come by !', max_length=500),
        ),
    ]
