# Generated by Django 3.2.4 on 2022-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_auto_20220801_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Description',
            field=models.CharField(default='Come by !', max_length=500),
        ),
    ]
