# Generated by Django 3.2.4 on 2022-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_alter_flyer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Description',
            field=models.CharField(blank=True, default='Come by !', max_length=500, null=True),
        ),
    ]
