# Generated by Django 3.2.4 on 2022-09-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_flyer_image_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='Lattitude',
            field=models.CharField(default=0, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flyer',
            name='Longitude',
            field=models.CharField(default=0, max_length=19),
            preserve_default=False,
        ),
    ]
