# Generated by Django 3.2.4 on 2022-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_auto_20220929_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='Lattitude',
            field=models.CharField(max_length=29),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='Longitude',
            field=models.CharField(max_length=29),
        ),
    ]
